# Generated by Django 4.1.5 on 2023-02-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
